### PR TITLE
👷 Add wokwi testing workflow to CI

### PR DESCRIPTION
**Pull request by satmatthills**

### CODE REVIEW

**Comment by satmatthills** [comment]
This doesn't work yet because the .bin and .elf files can't be found on the runner machine yet, for some reason.  I'll put it down for today and look into it tomorrow.

**Comment by jcelerier** [comment]
ok, now we can update this branch :)

**Comment by satmatthills** [comment]
Ok this works on my fork now, and should work on this one as soon as we setup a secret for WOKWI_CLI_TOKEN in the repo settings

**Comment by jcelerier** [comment]
@edumeneses I think you are the only one who can add the CI token

**Comment by edumeneses** [comment]
@satmatthills , can you please send me the token? Maybe via Slack?

**Comment by edumeneses** [comment]
Secret done

**Review by edumeneses — APPROVED** [review]
Looks good to me

**Comment by jcelerier** [comment]
rebased on top of main so that we get a new build

**Comment by jcelerier** [comment]
this seems to have broken the build :| can you check @satmatthills ?

**Comment by edumeneses** [comment]
@satmatthills , please check the folder names, they changed from **ble-advertising-template** to **ble-advertising**
 (same for [libmapper-osc](https://github.com/Puara/puara-module-templates/tree/main/libmapper-osc))
 
 Here on the [build.yml](https://github.com/Puara/puara-module-templates/blob/main/.github/workflows/build.yml):
 
 ```
      - name: Build ble-advertising-template
       run: cd ./ble-advertising-template && pio run
      
      - name: Build libmapper-osc-template
        run: cd ./libmapper-osc-template && pio run  
```

**Review by edumeneses — APPROVED** [review]

**Comment by edumeneses** [comment]
@satmatthills , CI failed at `Simulate and test ble-advertising with Wowki`

**Comment by jcelerier** [comment]
i'd propose to disable the Wokwi testing step, merge this and then work specifically on that on another PR. This way we at least have CI of the build. Are you ok with that ?

**Comment by edumeneses** [comment]
I'm ok with that solution

**Comment by satmatthills** [comment]
I’m also ok with the proposed solution but since it’s still failing due to the Wokwi token I’m prettttttttty sure it’s just that @edumeneses has to create the token himself and assign it to his account; the current token is associated with mine.  If THAT fails it may just take a second to reconfigure it.   Either way do what yall gotta.  Maybe we can look at it quickly tomorrow @edumeneses ?

**Comment by jcelerier** [comment]
I think we can merge - I just realized that secrets won't be available in PRs that come from outside the repository for security reasons.

**Review by edumeneses — APPROVED** [review]

**Pull request merged**
