### PR TITLE
🐛🔥 reconfigure Wokwi.toml and delete extraneous directories

### PR DESCRIPTION
**Pull request by satmatthills**

### CODE REVIEW

**Comment by satmatthills** [comment]
This currently times out when simulating and testing w Wokwi; it is likely a bad configuration - I'll label it WIP til it's working

**Comment by satmatthills** [comment]
Works, now.

**Comment by jcelerier** [comment]
image

beautiful :') thanks !

**Review by jcelerier — APPROVED** [review]

**Review by edumeneses — APPROVED** [review]
Looks good to me.

One thing to add is that it seems we have a bug with ESP-S3. Since we are building with C3 it is not a problem, but we need to investigate.

**Comment by jcelerier** [comment]
Hmm maybe the next thing would be to add a C3 environment & test. S3 & C3 are pretty different AFAIK, S3 is with the classic ESP Xtensa CPU while the C3 use new RISC-V CPUs

**Pull request merged**
